# Generated by Django 5.1.2 on 2024-11-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lugar', models.CharField(max_length=50)),
                ('Sector', models.CharField(max_length=100)),
                ('CallePrincipal', models.CharField(max_length=100)),
                ('Interseccion', models.CharField(max_length=100)),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
    ]
