# Generated by Django 5.1.2 on 2024-11-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion_model',
            name='lugar',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
