# Generated by Django 5.1.2 on 2024-10-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prioridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridad',
            name='Estado',
            field=models.BooleanField(default=1),
        ),
    ]
