# Generated by Django 5.1.2 on 2024-10-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prioridad', '0002_prioridad_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prioridad',
            new_name='Prioridad_Model',
        ),
    ]
