# Generated by Django 5.1.2 on 2024-11-23 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Calendario', '0001_initial'),
        ('Novedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabIncidente_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], help_text='Nivel de prioridad de la incidencia', max_length=1)),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha y hora de creación del reporte')),
                ('agente', models.ForeignKey(help_text='Agente responsable del reporte', on_delete=django.db.models.deletion.PROTECT, related_name='agentes', to='Calendario.turnusuario_model')),
                ('novedad', models.ForeignKey(help_text='Novedad asociada al incidente', on_delete=django.db.models.deletion.PROTECT, to='Novedad.novedad_model')),
            ],
            options={
                'verbose_name': 'Cabecera de Incidente',
                'verbose_name_plural': 'Cabeceras de Incidentes',
            },
        ),
        migrations.CreateModel(
            name='DetIncidente_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_incidente', models.CharField(choices=[('R', 'Resuelto'), ('E', 'En Proceso'), ('N', 'Notificado'), ('A', 'Atendido')], default='N', help_text='Estado actualizado de la incidencia', max_length=1)),
                ('hora', models.TimeField(auto_now_add=True, help_text='Fecha y hora de este detalle')),
                ('evidencia', models.FileField(blank=True, help_text='Evidencia adjunta (opcional)', null=True, upload_to='media/evidencias', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi'])])),
                ('descripcion', models.TextField(help_text='Descripción detallada del seguimiento del incidente')),
                ('comentarios_adicionales', models.TextField(blank=True, help_text='Comentarios adicionales sobre el seguimiento', null=True)),
                ('cabincidente', models.ForeignKey(help_text='Referencia a la cabecera del incidente', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='Reportes.cabincidente_model')),
            ],
            options={
                'verbose_name': 'Detalle de Incidente',
                'verbose_name_plural': 'Detalles de Incidentes',
            },
        ),
    ]
