# Generated by Django 5.1.2 on 2024-11-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detincidente_model',
            name='estado_incidente',
            field=models.CharField(choices=[('C', 'Cerrado'), ('E', 'En Proceso'), ('N', 'Notificado'), ('A', 'Atendido')], default='N', help_text='Estado actualizado de la incidencia', max_length=1),
        ),
    ]
