# Generated by Django 5.1.2 on 2024-11-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabincidente_model',
            name='fecha',
            field=models.DateField(auto_now_add=True, help_text='Fecha y hora de creación del reporte'),
        ),
    ]
