# Generated by Django 5.1.2 on 2024-11-20 02:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0002_cabincidente_model_detincidente_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detincidente_model',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
