# Generated by Django 5.1.2 on 2024-11-28 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0002_alter_detincidente_model_estado_incidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detincidente_model',
            name='evidencia',
            field=models.FileField(blank=True, help_text='Evidencia adjunta (opcional)', null=True, upload_to='evidencias', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi'])]),
        ),
    ]
