# Generated by Django 5.1.2 on 2024-11-18 12:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Calendario', '0001_initial'),
        ('Novedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabIncidente_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=1)),
                ('fecha', models.DateField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agente', to='Calendario.turnusuario_model')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Novedad.novedad_model')),
            ],
        ),
        migrations.CreateModel(
            name='DetIncidente_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_incidente', models.CharField(choices=[('R', 'Resuelto'), ('E', 'En Proceso'), ('N', 'Notificado')], default='N', max_length=1)),
                ('hora', models.TimeField(auto_now=True)),
                ('evidencia', models.FileField(upload_to='media/evidencias', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi'])])),
                ('descripcion', models.CharField(max_length=300)),
                ('estado', models.BooleanField(default=True)),
                ('cabincidente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Incidente.cabincidente_model')),
            ],
        ),
    ]
