# Generated by Django 5.1.2 on 2024-11-11 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Turno', '0001_initial'),
        ('Ubicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_inicio', models.DateField()),
                ('Fecha_fin', models.DateField()),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurnUsuario_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField(default=True)),
                ('Calendario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Calendario.calendario_model')),
                ('Turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Turno.turno_model')),
                ('Ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ubicacion.ubicacion_model')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
