# Generated by Django 5.1.2 on 2024-11-14 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Novedad', '0001_initial'),
        ('Ubicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabIncidente_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('Agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agente', to=settings.AUTH_USER_MODEL)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ubicacion.ubicacion_model')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Novedad.novedad_model')),
            ],
        ),
    ]
