# Generated by Django 5.1.2 on 2024-11-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora_inicio', models.TimeField()),
                ('Hora_fin', models.TimeField()),
                ('Estado', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Hora_inicio', 'Hora_fin'), name='unique_hora_inicio_hora_fin')],
            },
        ),
    ]
