# Generated by Django 5.1.2 on 2024-11-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turno', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turno_model',
            constraint=models.UniqueConstraint(fields=('Hora_inicio', 'Hora_fin'), name='unique_hora_inicio_hora_fin'),
        ),
    ]
