# Generated by Django 5.1.2 on 2024-11-07 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('M', 'Modificar'), ('C', 'Crear'), ('E', 'Eliminar')], max_length=1, verbose_name='Acción')),
                ('tabla', models.CharField(max_length=100, verbose_name='Tabla')),
                ('registro_id', models.IntegerField(verbose_name='ID de Registro')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('estacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Usuario',
                'verbose_name_plural': 'Auditorías de Usuarios',
                'ordering': ('-fecha',),
            },
        ),
    ]
