# Generated by Django 5.1.2 on 2024-11-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriauser',
            name='nombre_maquina',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Máquina'),
        ),
    ]
