# Generated by Django 5.1.2 on 2024-11-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriauser',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la Acción'),
        ),
        migrations.AlterField(
            model_name='auditoriauser',
            name='accion',
            field=models.CharField(choices=[('M', 'Modificar'), ('C', 'Crear'), ('E', 'Eliminar'), ('I', 'Inactivar'), ('A', 'Activar')], max_length=1, verbose_name='Acción'),
        ),
    ]
