# Generated by Django 5.1.2 on 2024-11-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0002_auditoriauser_descripcion_alter_auditoriauser_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriauser',
            name='accion',
            field=models.CharField(choices=[('M', 'Modificar'), ('C', 'Crear'), ('E', 'Eliminar'), ('I', 'Inactivar'), ('A', 'Activar'), ('B', 'Bloqueo'), ('ADV', 'Advertencia')], max_length=3, verbose_name='Acción'),
        ),
    ]
