# Generated by Django 5.1.2 on 2024-10-29 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=15, null=True)),
                ('apellido', models.CharField(blank=True, max_length=15, null=True)),
                ('cedula', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^.{10}$')])),
                ('estado', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('rol', models.CharField(blank=True, choices=[('S', 'Supervisor'), ('AC', 'Agente de Control')], default='Supervisor', max_length=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
