# Generated by Django 5.1.2 on 2024-11-15 03:31

import Modulos.Login.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(max_length=25, unique=True, validators=[Modulos.Login.utils.validar_campo], verbose_name='Nombre del rol'),
        ),
    ]
