# Generated by Django 5.1.2 on 2024-10-29 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^.{10}$')]),
        ),
    ]
