# Generated by Django 5.1.2 on 2024-11-10 03:27

import Modulos.Login.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_rename_date_joined_usuario_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[Modulos.Login.utils.validar_cedula]),
        ),
    ]
