# Generated by Django 5.1.2 on 2024-11-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_usuario_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
